Bomb
Svahnen/Orange-Game-Development-App pull request #15
Opened 2018-01-23 12:30 UTC by Alexosk

2018-01-23 12:33 UTC, mangster80 approved these changes
Noice!

2018-01-23 12:37 UTC, mirandamutka approved these changes

2018-01-23 12:43 UTC, falt requested changes

2018-01-23 12:43 UTC, falt commented on html/script/map2.js
> +    alert('Du har förlurat')
Change spelling to "förlorat"

2018-01-23 12:46 UTC, Alexosk commented on html/script/map2.js
> +    alert('Du har förlurat')
Fixad

2018-01-23 12:53 UTC, falt approved these changes

2018-01-23 12:55 UTC, Svahnen approved these changes

2018-01-23 13:09 UTC, merged

2018-01-24 09:37 UTC, Svahnen commented
https://cdn.discordapp.com/attachments/389719765217705986/405657299143753728/iconer.png